Homework/banner 2
Natandronovich/fe-46-andronovich pull request #4
Opened 2023-02-06 09:20 UTC by Natandronovich

2023-02-06 09:49 UTC, UladTeachMeSkills requested changes

2023-02-06 09:49 UTC, UladTeachMeSkills commented on axit-project/index.html
> +    <link href="./styles/banner_2.css" rel="stylesheet">
Обрати внимание на файловую структуру, которую я сбросил в группу. Создай файл index.css и импортируй в него при помощи @import все свои файлы со стилями. Добавь link только на свой единственный файл index.css в index.html

2023-02-06 09:49 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                    <span class="divider"></span> <!-- <span class="divider divider_pink"></span> -->
Эмм, а зачем комментарий?

2023-02-06 09:49 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                    <span class="divider"></span> <!-- <span class="divider divider_pink"></span> -->
??

2023-02-06 09:49 UTC, UladTeachMeSkills commented on axit-project/styles/banner_2.css
> +    font-family: 'Open Sans', sans-serif;
Создай файл main.css и пропиши туда все свои общие стили, что бы в каждом файле их не переопределять

2023-02-06 09:49 UTC, UladTeachMeSkills commented on axit-project/styles/banner_2.css
> +    min-width: 1510px;
max-width

2023-02-06 09:49 UTC, UladTeachMeSkills commented on axit-project/styles/banner_2.css
> +    font-family: 'Open Sans';
Зачем если он у тебя уже есть в body?

2023-02-06 11:29 UTC, Natandronovich commented on axit-project/index.html
> +                    <span class="divider"></span> <!-- <span class="divider divider_pink"></span> -->
Это я для себя писала, что надо вместо обычного divider можно использовать с модификатором divider_pink, и забыла удалить

2023-02-07 08:53 UTC, UladTeachMeSkills approved these changes

2023-02-07 08:53 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                    <span class="divider"></span>
Лишнего ничего не удалила?

2023-02-07 10:42 UTC, merged